#!/usr/bin/env bash

set -eu
set -o pipefail

command_console() {
  echo '```console'
  echo "$ $*"
  "$@"
  echo '```'
}

commands() {
  for cmd in scaffold create-pr-new-pkg init generate-registry patch-checksum completion; do
    echo "
## aqua-registry $cmd

$(command_console aqua-registry help $cmd)"
  done
}

echo "# Usage

<!-- This is generated by generate-usage.sh. Don't edit this file directly. -->

$(command_console aqua-registry help)
$(commands)
" > USAGE.md
