package genrg

import (
	"bufio"
	"context"
	"fmt"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"strings"
)

const rHeader = `---
# Don't edit registry.yaml manually.
# registry.yaml is generated by command "aqua-registry gr".
packages:
`

// registryFile is a discovered pkgs/<pkg>/registry.yaml. Dir is precomputed so
// the sort comparator does not recompute filepath.Dir on every comparison.
type registryFile struct {
	Path string
	Dir  string
}

func GenerateRegistry(ctx context.Context) error {
	files, err := listRegistryFiles(ctx)
	if err != nil {
		return err
	}
	rgFile, err := os.Create("registry.yaml")
	if err != nil {
		return fmt.Errorf("open registry.yaml: %w", err)
	}
	defer rgFile.Close()
	if _, err := rgFile.WriteString(rHeader); err != nil {
		return fmt.Errorf("write a header to registry.yaml: %w", err)
	}
	for _, f := range files {
		lines, err := readRegistryFile(f.Path)
		if err != nil {
			return fmt.Errorf("read a registry.yaml: %w", err)
		}
		if _, err := rgFile.WriteString(strings.Join(lines, "\n") + "\n"); err != nil {
			return fmt.Errorf("write registry.yaml: %w", err)
		}
	}
	return nil
}

func listRegistryFiles(ctx context.Context) ([]registryFile, error) {
	canonical := canonicalCaseMap(ctx)
	files := []registryFile{}
	if err := filepath.WalkDir("pkgs", func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			if d == nil {
				return err
			}
			return nil
		}
		if filepath.Base(p) != "registry.yaml" {
			return nil
		}
		slash := filepath.ToSlash(p)
		if c, ok := canonical[strings.ToLower(slash)]; ok {
			slash = c
		}
		files = append(files, registryFile{Path: slash, Dir: filepath.Dir(slash)})
		return nil
	}); err != nil {
		return nil, fmt.Errorf("find registry.yaml in the directory pkgs: %w", err)
	}
	slices.SortFunc(files, func(a, b registryFile) int {
		return strings.Compare(a.Dir, b.Dir)
	})
	return files, nil
}

// canonicalCaseMap returns a lower-cased path → git-recorded path mapping for
// every file tracked under pkgs/. On case-insensitive filesystems (APFS, NTFS)
// the working tree may surface a different case than git's index, which would
// otherwise make registry.yaml ordering depend on the contributor's machine.
// Returns nil if git is unavailable or pkgs/ is not tracked.
func canonicalCaseMap(ctx context.Context) map[string]string {
	out, err := exec.CommandContext(ctx, "git", "ls-files", "-z", "--", "pkgs").Output()
	if err != nil {
		return nil
	}
	s := strings.TrimRight(string(out), "\x00")
	if s == "" {
		return nil
	}
	m := make(map[string]string)
	for p := range strings.SplitSeq(s, "\x00") {
		m[strings.ToLower(p)] = p
	}
	return m
}

func readRegistryFile(registryFilePath string) ([]string, error) {
	lines := []string{}
	f, err := os.Open(registryFilePath)
	if err != nil {
		return nil, fmt.Errorf("open %s: %w", registryFilePath, err)
	}
	defer f.Close()
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := scanner.Text()
		if strings.HasPrefix(line, "packages:") || line == "---" || strings.HasPrefix(line, "# yaml-language-server:") {
			continue
		}
		lines = append(lines, line)
	}
	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("scan a file: %w", err)
	}
	return lines, nil
}
