package genrg

import (
	"bufio"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const rHeader = `---
# Don't edit registry.yaml manually.
# registry.yaml is generated by command "aqua-registry gr".
packages:
`

func GenerateRegistry() error {
	registryFilePaths, err := listRegistryFiles()
	if err != nil {
		return err
	}
	rgFile, err := os.Create("registry.yaml")
	if err != nil {
		return fmt.Errorf("open registry.yaml: %w", err)
	}
	defer rgFile.Close()
	if _, err := rgFile.WriteString(rHeader); err != nil {
		return fmt.Errorf("write a header to registry.yaml: %w", err)
	}
	for _, registryFilePath := range registryFilePaths {
		lines, err := readRegistryFile(registryFilePath)
		if err != nil {
			return fmt.Errorf("read a registry.yaml: %w", err)
		}
		if _, err := rgFile.WriteString(strings.Join(lines, "\n") + "\n"); err != nil {
			return fmt.Errorf("write registry.yaml: %w", err)
		}
	}
	return nil
}

func listRegistryFiles() ([]string, error) {
	registryFilePaths := []string{}
	if err := filepath.WalkDir("pkgs", func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			if d == nil {
				return err
			}
			return nil
		}
		if filepath.Base(p) == "registry.yaml" {
			registryFilePaths = append(registryFilePaths, p)
		}
		return nil
	}); err != nil {
		return nil, fmt.Errorf("find registry.yaml in the directory pkgs: %w", err)
	}
	sort.Slice(registryFilePaths, func(i, j int) bool {
		return filepath.ToSlash(filepath.Dir(registryFilePaths[i])) < filepath.ToSlash(filepath.Dir(registryFilePaths[j]))
	})
	return registryFilePaths, nil
}

func readRegistryFile(registryFilePath string) ([]string, error) {
	lines := []string{}
	f, err := os.Open(registryFilePath)
	if err != nil {
		return nil, fmt.Errorf("open %s: %w", registryFilePath, err)
	}
	defer f.Close()
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := scanner.Text()
		if strings.HasPrefix(line, "packages:") || line == "---" || strings.HasPrefix(line, "# yaml-language-server:") {
			continue
		}
		lines = append(lines, line)
	}
	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("scan a file: %w", err)
	}
	return lines, nil
}
