package initcmd

import (
	"context"
	"fmt"
	"os"
)

const filePermission os.FileMode = 0o644

func Init(_ context.Context) error {
	if err := initRegistryYAML(); err != nil {
		return err
	}
	if err := initAquaYAML(); err != nil {
		return err
	}
	return nil
}

func initAquaYAML() error {
	if _, err := os.Stat("aqua.yaml"); err == nil {
		return nil
	}
	fmt.Fprintln(os.Stderr, "Creating aqua.yaml")
	if err := os.WriteFile("aqua.yaml", []byte(`---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
  - name: local
    type: local
    path: registry.yaml
packages:
`), filePermission); err != nil {
		return fmt.Errorf("create aqua.yaml: %w", err)
	}
	return nil
}

func initRegistryYAML() error {
	if _, err := os.Stat("registry.yaml"); err == nil {
		return nil
	}
	fmt.Fprintln(os.Stderr, "Creating registry.yaml")
	if err := os.WriteFile("registry.yaml", []byte(`---
# Don't edit registry.yaml manually.
# registry.yaml is generated by command "aqua-registry gr".
packages:
`), filePermission); err != nil {
		return fmt.Errorf("create registry.yaml: %w", err)
	}
	return nil
}
