---
# Separate the workflow for actionlint to other workflows, because if a workflow for actionlint is broken actionlint isn't run
name: actionlint
on:
  pull_request:
    paths:
      - .github/workflows/*.yaml
      - aqua/actionlint.yaml
      - aqua/reviewdog.yaml
permissions: {}
jobs:
  actionlint:
    uses: suzuki-shunsuke/actionlint-workflow/.github/workflows/actionlint.yaml@813a6d08c08cfd7a08618a89a59bfe78e573597c # v1.0.1
    if: |
      ! github.event.pull_request.head.repo.fork
    with:
      aqua_version: v2.27.3
    permissions:
      pull-requests: write
      contents: read

  actionlint_fork:
    # Lint GitHub Actions Workflows by actionlint.
    if: github.event.pull_request.head.repo.fork
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - uses: aquaproj/aqua-installer@6ce1f8848ec8e61f14d57bd5d7597057a6dd187c # v3.0.1
        with:
          aqua_version: v2.27.3
      - run: actionlint
        env:
          GITHUB_TOKEN: ${{github.token}}
