---
# Separate the workflow for actionlint to other workflows, because if a workflow for actionlint is broken actionlint isn't run
name: actionlint
on:
  pull_request:
    paths:
      - .github/workflows/*.yaml
      - aqua/actionlint.yaml
      - aqua/reviewdog.yaml
permissions: {}
jobs:
  actionlint:
    uses: suzuki-shunsuke/actionlint-workflow/.github/workflows/actionlint.yaml@6b8692cb5c9d3ffb2ff624ffeee3e10ae10615f3 # v1.1.0
    if: |
      ! github.event.pull_request.head.repo.fork
    with:
      aqua_version: v2.31.0
    permissions:
      pull-requests: write
      contents: read

  actionlint_fork:
    # Lint GitHub Actions Workflows by actionlint.
    timeout-minutes: 30
    if: github.event.pull_request.head.repo.fork
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: aquaproj/aqua-installer@6ce1f8848ec8e61f14d57bd5d7597057a6dd187c # v3.0.1
        with:
          aqua_version: v2.31.0
      - run: actionlint
        env:
          GITHUB_TOKEN: ${{github.token}}
