---
# Separate the workflow for actionlint to other workflows, because if a workflow for actionlint is broken actionlint isn't run
name: actionlint
on:
  pull_request:
    paths:
      - .github/workflows/*.yaml
      - aqua/actionlint.yaml
      - aqua/reviewdog.yaml
permissions: {}
jobs:
  actionlint:
    uses: suzuki-shunsuke/actionlint-workflow/.github/workflows/actionlint.yaml@beaeeecc42b2645b4c8ecf9d9692fabb16a5eadd # v0.5.1
    if: |
      ! github.event.pull_request.head.repo.fork
    with:
      aqua_version: v2.21.0
    permissions:
      pull-requests: write
      contents: read

  actionlint_fork:
    # Lint GitHub Actions Workflows by actionlint.
    if: github.event.pull_request.head.repo.fork
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: aquaproj/aqua-installer@928a2ee4243a9ee8312d80dc8cbaca88fb602a91 # v2.2.0
        with:
          aqua_version: v2.21.0
      - run: actionlint
        env:
          GITHUB_TOKEN: ${{github.token}}
