---
# Separate the workflow for actionlint to other workflows, because if a workflow for actionlint is broken actionlint isn't run
name: actionlint
on:
  pull_request:
    paths:
      - .github/workflows/*.yaml
      - aqua/actionlint.yaml
      - aqua/reviewdog.yaml
permissions: {}
jobs:
  actionlint:
    uses: suzuki-shunsuke/actionlint-workflow/.github/workflows/actionlint.yaml@8d67cddd56ea4b045e858700595d49b2fe09de61 # v1.0.0
    if: |
      ! github.event.pull_request.head.repo.fork
    with:
      aqua_version: v2.27.2
    permissions:
      pull-requests: write
      contents: read

  actionlint_fork:
    # Lint GitHub Actions Workflows by actionlint.
    if: github.event.pull_request.head.repo.fork
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
      - uses: aquaproj/aqua-installer@4551ec64e21bf0f557c2525135ff0bd2cba40ec7 # v3.0.0
        with:
          aqua_version: v2.27.2
      - run: actionlint
        env:
          GITHUB_TOKEN: ${{github.token}}
