---
# Separate the workflow for actionlint to other workflows, because if a workflow for actionlint is broken actionlint isn't run
name: actionlint
on:
  pull_request:
    paths:
      - .github/workflows/*.yaml
      - aqua/actionlint.yaml
      - aqua/reviewdog.yaml
permissions: {}
jobs:
  actionlint:
    uses: suzuki-shunsuke/actionlint-workflow/.github/workflows/actionlint.yaml@b6a5f966d4504893b2aeb60cf2b0de8946e48504 # v0.5.0
    if: |
      ! github.event.pull_request.head.repo.fork
    with:
      aqua_version: v2.17.0
    permissions:
      pull-requests: write
      contents: read

  actionlint_fork:
    # Lint GitHub Actions Workflows by actionlint.
    if: github.event.pull_request.head.repo.fork
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - uses: aquaproj/aqua-installer@928a2ee4243a9ee8312d80dc8cbaca88fb602a91 # v2.2.0
        with:
          aqua_version: v2.17.0
      - run: actionlint
        env:
          GITHUB_TOKEN: ${{github.token}}
