---
name: test
on: pull_request
permissions: {}

jobs:
  path-filter:
    # Get changed files to filter jobs
    timeout-minutes: 30
    outputs:
      update-aqua-checksums: ${{steps.changes.outputs.update-aqua-checksums}}
      renovate-config-validator: ${{steps.changes.outputs.renovate-config-validator}}
      ghalint: ${{steps.changes.outputs.ghalint}}
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          filters: |
            update-aqua-checksums:
              - aqua.yaml
              - aqua/*.yaml
              - aqua-checksums.json
              - .github/workflows/test.yaml
            renovate-config-validator:
              - renovate.json5
            ghalint:
              - .github/workflows/*.yaml
              - aqua/ghalint.yaml

  ghalint:
    # Validate GitHub Actions Workflows by ghalint.
    timeout-minutes: 30
    needs: path-filter
    if: needs.path-filter.outputs.ghalint == 'true'
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: aquaproj/aqua-installer@e2d0136abcf70b7a2f6f505720640750557c4b33 # v3.1.1
        with:
          aqua_version: v2.43.1
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}
      - run: ghalint run
        env:
          GHALINT_LOG_COLOR: always

  update-aqua-checksums:
    # Update aqua-checksums.json and push a commit
    needs: path-filter
    permissions:
      contents: read # The reusable workflow requires contents:read
    if: |
      needs.path-filter.outputs.update-aqua-checksums == 'true'
    uses: aquaproj/update-checksum-workflow/.github/workflows/update-checksum.yaml@8bce60cc4475128360bc32f00707abb874ca4a91 # v1.0.3
    with:
      aqua_version: v2.43.1
      prune: true
    secrets:
      gh_app_id: ${{secrets.APP_ID}}
      gh_app_private_key: ${{secrets.APP_PRIVATE_KEY}}

  renovate-config-validator:
    # Validate Renovate Configuration by renovate-config-validator.
    uses: suzuki-shunsuke/renovate-config-validator-workflow/.github/workflows/validate.yaml@e8effbd185cbe3874cddef63f48b8bdcfc9ada55 # v0.2.4
    needs: path-filter
    if: needs.path-filter.outputs.renovate-config-validator == 'true'
    permissions:
      contents: read

  enable-automerge:
    # Enable automerge to merge pull requests from Renovate automatically.
    timeout-minutes: 30
    runs-on: ubuntu-latest
    needs:
      - status-check
    permissions:
      contents: write # For enable automerge
      pull-requests: write # For enable automerge
    # "! failure() && ! cancelled()" is required. success() returns false if dependent jobs are skipped. https://github.com/community/community/discussions/45058
    # By default success() is used so we have to override success() by "! failure() && ! cancelled()"
    if: |
      ! failure() && ! cancelled() && github.event.pull_request.user.login == 'renovate[bot]' && contains(github.event.pull_request.body, ' **Automerge**: Enabled.')
    steps:
      - uses: suzuki-shunsuke/enable-auto-merge-action@ec074392e76cd1062925255cd82a86ea1c44b6fd # v0.1.0
        with:
          pr_number: ${{github.event.pull_request.number}}
          merge_method: squash
          github_app_id: ${{secrets.APP_ID}}
          github_app_private_key: ${{secrets.APP_PRIVATE_KEY}}

  status-check:
    # This job is used for main branch's branch protection rule's status check.
    # If all dependent jobs succeed or are skipped this job succeeds.
    timeout-minutes: 30
    runs-on: ubuntu-latest
    needs:
      - update-aqua-checksums
      - test
      - ghalint
      - renovate-config-validator
    permissions: {}
    if: failure()
    steps:
      - run: exit 1

  test:
    uses: suzuki-shunsuke/go-test-workflow/.github/workflows/test.yaml@6861ea245ad10752afcba66cb71f28cf5c46ce49 # v1.1.0
    with:
      aqua_version: v2.43.1
      go-version-file: go.mod
    permissions:
      pull-requests: write
      contents: read

  prettier:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - run: npm i -g prettier
      - run: prettier -c .
