---
name: test-release
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/test-release.yaml
      - .goreleaser.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
      - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
        with:
          go-version: "1.19.2"
          cache: true

      - name: remove changes
        # Sometimes it is failed to release by goreleaser due to changes of go.sum
        run: git checkout -- .
      - name: Run GoReleaser (skip publish)
        uses: goreleaser/goreleaser-action@b508e2e3ef3b19d4e4146d4f8fb3ba9db644a757 # tag=v3.2.0
        if: "! startsWith(github.ref, 'refs/tags/')"
        with:
          version: latest
          args: release --rm-dist --snapshot
