---
name: test
on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:
    branches: [main]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3.2.1
        with:
          go-version: "1.18.5"
          cache: true
      - uses: aquaproj/aqua-installer@v1.1.1
        with:
          aqua_version: v1.19.2

      - run: go install ./cmd/aqua-registry
      - uses: suzuki-shunsuke/github-action-golangci-lint@v0.1.3
      - run: go test -v ./... -race -covermode=atomic

      - name: remove changes
        # Sometimes it is failed to release by goreleaser due to changes of go.sum
        run: git checkout -- .
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --rm-dist
