---
name: test-release
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/test-release.yaml
      - .goreleaser.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
      - uses: actions/setup-go@d0a58c1c4d2b25278816e339b944508c875f3613 # v3.4.0
        with:
          go-version: "1.19.2"
          cache: true

      - name: remove changes
        # Sometimes it is failed to release by goreleaser due to changes of go.sum
        run: git checkout -- .
      - name: Run GoReleaser (skip publish)
        uses: goreleaser/goreleaser-action@8f67e590f2d095516493f017008adc464e63adb1 # v4.1.0
        if: "! startsWith(github.ref, 'refs/tags/')"
        with:
          version: latest
          args: release --rm-dist --snapshot
